import React from 'react';
import * as Fi from 'react-icons/fi';

type IconName =
    | 'zap'
    | 'building-2'
    | 'chevrons-up-down'
    | 'layout-dashboard'
    | 'check-square'
    | 'timer'
    | 'calendar'
    | 'bar-chart-2'
    | 'users'
    | 'folder'
    | 'bell'
    | 'settings'
    | 'log-out'
    | 'search'
    | 'plus'
    | 'clock'
    | 'trending-up'
    | 'square'
    | 'save'
    | 'arrow-right'
    | 'sliders-horizontal'
    | 'arrow-up-down'
    | 'layout-grid'
    | 'list'
    | 'more-horizontal'
    | 'message-square'
    | 'paperclip'
    | 'play'
    | 'pause'
    | 'minus'
    | 'arrow-up'
    | 'arrow-down'
    | 'check-circle-2'
    | 'play-circle'
    | 'message-circle'
    | 'plus-circle'
    | 'file-text'
    | 'layers'
    | 'loader'
    | 'list-todo'
    | 'trending-down'
    | 'copy'
    | 'tag'
    | 'trash-2'
    | 'chevron-down'
    | 'pencil'
    | 'trash-2'
    | 'coffee'
    | 'target'
    | 'keyboard'
    | 'user'
    | 'play'
    | 'pause'
    | 'square'
    | 'save'
    | 'plus'
    | 'clock'
    | 'calendar'
    | 'layers'
    | 'trending-up'
    | 'chevron-left'
    | 'chevron-right'
    | 'calendar-check'
    | 'check'
    | 'loader'
    | 'filter'
    | 'download'
    | 'file-spreadsheet'
    | 'alert-circle'
    | 'award'
    | 'eye'
    | 'activity'
    | 'user-plus'
    | 'edit-3'
    | 'hash'
    | 'smile-plus'
    | 'smile'
    | 'reply'
    | 'bold'
    | 'italic'
    | 'link'
    | 'code'
    | 'at-sign'
    | 'pin'
    | 'figma'
    | 'code-2'
    | 'download'
    | 'send'
    | 'image'
    | 'mail'
    | 'lock'
    | 'shield'
    | 'chrome'
    | 'github'
    | 'info'
    | 'palette'
    | 'plug'
    | 'credit-card'
    | 'monitor'
    | 'smartphone'
    | 'shield-alert'
    | 'shield-check'
    | 'align-justify'
    | 'menu'
    | 'layout-list'
    | 'rotate-ccw'
    | 'x';

const iconMap: Record<IconName, React.ElementType> = {
    zap: Fi.FiZap,
    timer: Fi.FiClock,
    calendar: Fi.FiCalendar,
    users: Fi.FiUsers,
    folder: Fi.FiFolder,
    bell: Fi.FiBell,
    settings: Fi.FiSettings,
    search: Fi.FiSearch,
    plus: Fi.FiPlus,
    clock: Fi.FiClock,
    square: Fi.FiSquare,
    save: Fi.FiSave,
    list: Fi.FiList,
    paperclip: Fi.FiPaperclip,
    play: Fi.FiPlay,
    pause: Fi.FiPause,
    minus: Fi.FiMinus,
    'building-2': Fi.FiHome,
    'chevrons-up-down': Fi.FiChevronDown,
    'layout-dashboard': Fi.FiGrid,
    'check-square': Fi.FiCheckSquare,
    'bar-chart-2': Fi.FiBarChart2,
    'log-out': Fi.FiLogOut,
    'trending-up': Fi.FiTrendingUp,
    'arrow-right': Fi.FiArrowRight,
    'sliders-horizontal': Fi.FiSliders,
    'arrow-up-down': Fi.FiArrowUp,
    'layout-grid': Fi.FiGrid,
    'more-horizontal': Fi.FiMoreHorizontal,
    'message-square': Fi.FiMessageSquare,
    'arrow-up': Fi.FiArrowUp,
    'arrow-down': Fi.FiArrowDown,
    'check-circle-2': Fi.FiCheckCircle,
    'play-circle': Fi.FiPlayCircle,
    'message-circle': Fi.FiMessageCircle,
    'plus-circle': Fi.FiPlusCircle,
    'file-text': Fi.FiFileText,
    'layers': Fi.FiLayers,
    'loader': Fi.FiLoader,
    'list-todo': Fi.FiList,
    'trending-down': Fi.FiTrendingDown,
    'copy': Fi.FiCopy,
    'tag': Fi.FiTag,
    'trash-2': Fi.FiTrash2,
    'chevron-down': Fi.FiChevronDown,
    'x': Fi.FiX,
    'pencil': Fi.FiEdit,
    'coffee': Fi.FiCoffee,
    'target': Fi.FiTarget,
    'keyboard': Fi.FiType,
    'user': Fi.FiUser,
    'chevron-left': Fi.FiChevronLeft,
    'chevron-right': Fi.FiChevronRight,
    'calendar-check': Fi.FiCalendar,
    'check': Fi.FiCheck,
    'filter': Fi.FiFilter,
    'download': Fi.FiDownload,
    'file-spreadsheet': Fi.FiFileText,
    'alert-circle': Fi.FiAlertCircle,
    'award': Fi.FiAward,
    'eye': Fi.FiEye,
    'activity': Fi.FiActivity,
    'user-plus': Fi.FiUserPlus,
    'edit-3': Fi.FiEdit3,
    'hash': Fi.FiHash,
    'smile': Fi.FiSmile,
    'smile-plus': Fi.FiSmile,
    'reply': Fi.FiCornerUpLeft,
    'bold': Fi.FiBold,
    'italic': Fi.FiItalic,
    'link': Fi.FiLink,
    'code': Fi.FiCode,
    'at-sign': Fi.FiAtSign,
    'pin': Fi.FiMapPin,
    'figma': Fi.FiFigma,
    'code-2': Fi.FiCode,
    'send': Fi.FiSend,
    'image': Fi.FiImage,
    'mail': Fi.FiMail,
    'lock': Fi.FiLock,
    'shield': Fi.FiShield,
    'chrome': Fi.FiChrome,
    'github': Fi.FiGithub,
    'info': Fi.FiInfo,
    'palette': Fi.FiDroplet,
    'plug': Fi.FiZap,
    'shield-alert': Fi.FiAlertTriangle,
    'shield-check': Fi.FiCheckCircle,
    'monitor': Fi.FiMonitor,
    'smartphone': Fi.FiSmartphone,
    'credit-card': Fi.FiCreditCard,
    'align-justify': Fi.FiAlignJustify,
    'menu': Fi.FiMenu,
    'layout-list': Fi.FiLayout,
    'rotate-ccw': Fi.FiRotateCcw,
};

interface IconProps {
    name: IconName;
    size?: number;
    className?: string;
}

const Icon: React.FC<IconProps> = ({ name, size = 16, className = '' }) => {
    const Comp = iconMap[name];
    if (!Comp) return null;
    return <Comp size={size} className={`text-current ${className}`} />;
};

export default Icon;