import React from 'react';
import * as Fi from 'react-icons/fi';

const iconMap = {
    'dollar-sign': Fi.FiDollarSign,
    'arrow-up-right': Fi.FiArrowUpRight,
    'pie-chart': Fi.FiPieChart,
    zap: Fi.FiZap,
    timer: Fi.FiClock,
    calendar: Fi.FiCalendar,
    users: Fi.FiUsers,
    folder: Fi.FiFolder,
    bell: Fi.FiBell,
    settings: Fi.FiSettings,
    search: Fi.FiSearch,
    plus: Fi.FiPlus,
    clock: Fi.FiClock,
    square: Fi.FiSquare,
    save: Fi.FiSave,
    list: Fi.FiList,
    paperclip: Fi.FiPaperclip,
    play: Fi.FiPlay,
    pause: Fi.FiPause,
    minus: Fi.FiMinus,
    'banknote': Fi.FiDollarSign,
    'globe': Fi.FiGlobe,
    'user-check': Fi.FiUserCheck,
    'landmark': Fi.FiHome,
    'x-circle': Fi.FiXCircle,
    'trending-down': Fi.FiTrendingDown,
    'settings-2': Fi.FiSettings,
    'filter': Fi.FiFilter,
    'more-horizontal': Fi.FiMoreHorizontal,
    'plus-circle': Fi.FiPlusCircle,
    'play-circle': Fi.FiPlayCircle,
    'underline': Fi.FiUnderline,
    'list-ordered': Fi.FiList,
    'upload-cloud': Fi.FiUploadCloud,
    'camera': Fi.FiCamera,
    'briefcase': Fi.FiBriefcase,
    'map-pin': Fi.FiMapPin,
    'target': Fi.FiTarget,
    'flame': Fi.FiZap,
    'check-check': Fi.FiCheckSquare,
    'external-link': Fi.FiExternalLink,
    'x': Fi.FiX,
    'user-plus': Fi.FiUserPlus,
    'alert-circle': Fi.FiAlertCircle,
    'mail': Fi.FiMail,
    'monitor': Fi.FiMonitor,
    'smartphone': Fi.FiSmartphone,
    'moon': Fi.FiMoon,
    'building-2': Fi.FiHome,
    'chevrons-up-down': Fi.FiChevronDown,
    'layout-dashboard': Fi.FiGrid,
    'check-square': Fi.FiCheckSquare,
    'bar-chart-2': Fi.FiBarChart2,
    'log-out': Fi.FiLogOut,
    'trending-up': Fi.FiTrendingUp,
    'arrow-right': Fi.FiArrowRight,
    'sliders-horizontal': Fi.FiSliders,
    'arrow-up-down': Fi.FiArrowUp,
    'layout-grid': Fi.FiGrid,
    'message-square': Fi.FiMessageSquare,
    'arrow-up': Fi.FiArrowUp,
    'arrow-down': Fi.FiArrowDown,
    'check-circle-2': Fi.FiCheckCircle,
    'message-circle': Fi.FiMessageCircle,
    'file-text': Fi.FiFileText,
    'layers': Fi.FiLayers,
    'loader': Fi.FiLoader,
    'list-todo': Fi.FiList,
    'copy': Fi.FiCopy,
    'tag': Fi.FiTag,
    'trash-2': Fi.FiTrash2,
    'chevron-down': Fi.FiChevronDown,
    'pencil': Fi.FiEdit,
    'coffee': Fi.FiCoffee,
    'keyboard': Fi.FiType,
    'user': Fi.FiUser,
    'chevron-left': Fi.FiChevronLeft,
    'chevron-right': Fi.FiChevronRight,
    'calendar-check': Fi.FiCalendar,
    'check': Fi.FiCheck,
    'download': Fi.FiDownload,
    'file-spreadsheet': Fi.FiFileText,
    'award': Fi.FiAward,
    'eye': Fi.FiEye,
    'activity': Fi.FiActivity,
    'edit-3': Fi.FiEdit3,
    'hash': Fi.FiHash,
    'smile': Fi.FiSmile,
    'smile-plus': Fi.FiSmile,
    'reply': Fi.FiCornerUpLeft,
    'bold': Fi.FiBold,
    'italic': Fi.FiItalic,
    'link': Fi.FiLink,
    'code': Fi.FiCode,
    'at-sign': Fi.FiAtSign,
    'pin': Fi.FiMapPin,
    'figma': Fi.FiFigma,
    'code-2': Fi.FiCode,
    'send': Fi.FiSend,
    'image': Fi.FiImage,
    'lock': Fi.FiLock,
    'shield': Fi.FiShield,
    'chrome': Fi.FiChrome,
    'github': Fi.FiGithub,
    'info': Fi.FiInfo,
    'palette': Fi.FiDroplet,
    'plug': Fi.FiZap,
    'shield-alert': Fi.FiAlertTriangle,
    'shield-check': Fi.FiCheckCircle,
    'credit-card': Fi.FiCreditCard,
    'align-justify': Fi.FiAlignJustify,
    'menu': Fi.FiMenu,
    'layout-list': Fi.FiLayout,
    'rotate-ccw': Fi.FiRotateCcw,
};

export type IconName = keyof typeof iconMap;

interface IconProps {
    name: IconName | (string & {});
    size?: number;
    className?: string;
}

const Icon: React.FC<IconProps> = ({ name, size = 16, className = '' }) => {
    const Comp = (iconMap as Record<string, React.ElementType>)[name] || Fi.FiCircle;
    return <Comp size={size} className={`text-current ${className}`} />;
};

export default Icon;